elastic:
  hostname: localhost
  hostport: 9300
  index: places
  type: place
mongo:
  collection: places
  db: places
  uri: mongodb://localhost/places
  indexName: loc_2dsphere
redis:
  uri: redis://localhost
  geoSetKey: places
rethink:
  hostname: localhost
  port: 28015
  db: places
  table: places
  numOfVertices: 8
  indexKey: location
rtree:
  star: true
  minChildren: 44
  maxChildren: 128
  geoHashBitPrecision: 32
global:
  defaultSearchRadius: 1
  maxAllowableSearchRadius: 10000
  resultSetSize: 100
  datastoreTarget: elastic