mongo:
  collection: places
  db: places
  uri: mongodb://localhost/places
  indexName: loc_2dsphere
global:
  defaultSearchRadius: 175
  maxAllowableSearchRadius: 1000
  defaultResultSize: 100
  maxResultSize: 1000